# Generated by Django 6.0.5 on 2026-05-23 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت\u200cها'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='ناشناس ثبت شده؟'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='message',
            field=models.TextField(default='', verbose_name='متن پیام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('open', 'در حال بررسی'), ('closed', 'بسته شده')], default='new', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان تیکت'),
        ),
    ]
