# Generated by Django 6.0.5 on 2026-05-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_options_remove_ticket_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
